Repository Web-Programming/EthoxRiad, pull requests merged in 2024-09, with the labels that each got.

#6 Feature/add sidebar, navbar, app layouting, and app routing system
  package-lock.json
  package.json
  src/App.tsx
  src/assets/mdp-logo-white.png
  src/assets/mdp-logo.png
  src/common/components/Layout/ContentWrapper.tsx
  src/common/components/Layout/MainSection.tsx
  src/common/components/Layout/Navbar.tsx
  src/common/components/Layout/Sidebar.tsx
  src/store/sidebar.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: good first issue

#7 Feature/dashboard
  package-lock.json
  src/App.tsx
  src/api/services/dashboard/entity.ts
  src/api/services/dashboard/service.ts
  src/pages/Dashboard/NewsCard.tsx
  src/pages/Dashboard/content.tsx
  src/pages/Dashboard/index.tsx
  src/pages/Dashboard/useNews.ts
Labels: good first issue

#8 Feature/schedule page
  package-lock.json
  package.json
  src/App.tsx
  src/api/course/data.ts
  src/api/course/model.ts
  src/api/course/service.ts
  src/api/index.ts
  src/api/schedule/data.ts
  src/api/schedule/model.ts
  src/api/services/example/entity.ts
  src/api/services/example/service.ts
  src/api/student/data.ts
  src/api/student/model.ts
  src/api/student/service.ts
  src/common/components/Layout/Sidebar.tsx
  src/common/components/Table/BaseTable/index.tsx
  src/common/components/Table/TableBody/index.tsx
  src/common/components/Table/TableRow/index.tsx
  src/common/types/index.ts
  src/common/utils/consts.ts
  src/common/utils/formatter.ts
  src/pages/PrismaOnline/content.tsx
  src/pages/PrismaOnline/index.tsx
  src/pages/PrismaOnline/partials/CourseList.tsx
  src/pages/PrismaOnline/partials/SearchCourse.tsx
  src/pages/ProofOfFilling/content.tsx
  src/pages/ProofOfFilling/index.tsx
  src/pages/ProofOfFilling/partials/SelectedCourseList.tsx
  src/pages/ProofOfFilling/partials/SelectedCourseTable.tsx
  src/pages/ProofOfFilling/partials/StudentInfo.tsx
  src/pages/Schedule/content.tsx
  src/pages/Schedule/index.tsx
  src/pages/Schedule/partials/DailySchedule.tsx
  src/pages/Schedule/partials/RegularSchedule.tsx
  src/pages/Schedule/partials/SwitchScheduleType.tsx
  src/pages/Schedule/partials/WeeklySchedule.tsx
  src/pages/Schedule/utils/activeSchedule.ts
Labels: enhancement

#9 Feature/Schedule page 2
  src/api/course/model.ts
  src/api/course/service.ts
  src/api/dashboard/model.ts
  src/api/dashboard/service.ts
  src/common/utils/consts.ts
  src/common/utils/selectedCourseData.ts
  src/pages/Dashboard/NewsCard.tsx
  src/pages/Dashboard/useNews.ts
  src/pages/PrismaOnline/partials/CourseList.tsx
  src/pages/PrismaOnline/partials/useCourses.ts
  src/pages/ProofOfFilling/partials/SelectedCourseList.tsx
  src/pages/ProofOfFilling/partials/SelectedCourseTable.tsx
  src/pages/ProofOfFilling/partials/StudentInfo.tsx
  src/pages/Schedule/partials/DailySchedule.tsx
  src/pages/Schedule/partials/RegularSchedule.tsx
  src/pages/Schedule/partials/WeeklySchedule.tsx
  tsconfig.json
Labels: documentation
